# Generated by Django 6.0 on 2025-12-12 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
    ]
